theme: jekyll-theme-cayman
title : Ahmed Mujtaba
description: This repository is just collection of educational materials.
show_downloads: true
github:
  zip_url: http://example.com/download.zip
  url: https://google.com
  url: https://duck.com.com
  
  
  
